/** Clearly labelled illustrative data for reviewing the redesigned dashboard. */

export const DASHBOARD_SAMPLE = {
  kpis: [
    {
      label: "Audit coverage",
      value: "82%",
      detail: "41 of 50 locations",
      tone: "brand",
      trend: [62, 68, 71, 76, 82],
    },
    {
      label: "Audits completed",
      value: "38 / 45",
      detail: "4 overdue · 3 active",
      tone: "neutral",
      trend: [18, 23, 27, 33, 38],
    },
    {
      label: "Critical actions",
      value: "12",
      detail: "5 require verification",
      tone: "bad",
      trend: [7, 9, 8, 14, 12],
    },
    {
      label: "Potential value variance",
      value: "₹1.84L",
      detail: "Observed, not confirmed loss",
      tone: "warn",
      trend: [1.2, 1.5, 1.35, 1.92, 1.84],
    },
    {
      label: "SLA compliance",
      value: "91%",
      detail: "+4.2% vs prior period",
      tone: "good",
      trend: [82, 84, 86, 88, 91],
    },
    {
      label: "Expiry exposure",
      value: "286 units",
      detail: "71 awaiting verification",
      tone: "bad",
      trend: [190, 214, 232, 301, 286],
    },
  ],
  auditStatus: [
    { name: "Assigned", value: 7 },
    { name: "In progress", value: 3 },
    { name: "Under review", value: 5 },
    { name: "Verified", value: 30 },
  ],
  actions: [
    {
      severity: "Critical",
      store: "Delhi Central 01",
      sku: "MAGGI-70G",
      issue: "Expired stock awaiting quarantine receipt",
      qty: 14,
      owner: "R. Sharma",
      due: "2h overdue",
    },
    {
      severity: "Critical",
      store: "Gurugram DLF 03",
      sku: "COLGATE-200G",
      issue: "Inventory shortage without verified RCA",
      qty: 21,
      owner: "P. Singh",
      due: "Today",
    },
    {
      severity: "High",
      store: "Noida Sector 18",
      sku: "LAYS-CREAM-52G",
      issue: "Quantity mismatch after recount",
      qty: 8,
      owner: "Unassigned",
      due: "Tomorrow",
    },
    {
      severity: "High",
      store: "Delhi Saket 02",
      sku: "TATA-TEA-1KG",
      issue: "Evidence rejected — blurred shelf image",
      qty: 6,
      owner: "A. Khan",
      due: "1 day",
    },
    {
      severity: "Medium",
      store: "Gurugram Golf 05",
      sku: "DOVE-100G",
      issue: "Near-expiry action required",
      qty: 18,
      owner: "M. Verma",
      due: "3 days",
    },
  ],
  availability: [
    { store: "Delhi Central", Snacks: 96, Beverages: 89, "Personal care": 93, Staples: 87 },
    { store: "Delhi Saket", Snacks: 91, Beverages: 84, "Personal care": 88, Staples: 94 },
    { store: "Gurugram DLF", Snacks: 83, Beverages: 92, "Personal care": 79, Staples: 86 },
    { store: "Noida Sec 18", Snacks: 88, Beverages: 81, "Personal care": 91, Staples: 82 },
  ],
  variance: [
    { sku: "MAGGI", shortage: -32, excess: 4 },
    { sku: "COLGATE", shortage: -24, excess: 2 },
    { sku: "LAYS", shortage: -18, excess: 7 },
    { sku: "TATA TEA", shortage: -12, excess: 3 },
    { sku: "DOVE", shortage: -8, excess: 11 },
  ],
  compliance: [
    { audit: "A-01", compliance: 76, availability: 82 },
    { audit: "A-02", compliance: 79, availability: 84 },
    { audit: "A-03", compliance: 75, availability: 81 },
    { audit: "A-04", compliance: 84, availability: 88 },
    { audit: "A-05", compliance: 87, availability: 91 },
    { audit: "A-06", compliance: 89, availability: 93 },
  ],
  shelfExecution: [
    { name: "Wrong placement", value: 34 },
    { name: "Missing", value: 26 },
    { name: "Pricing", value: 17 },
    { name: "Damaged", value: 13 },
    { name: "Display", value: 10 },
  ],
  skuTrend: [
    { audit: "A-1041", expected: 48, actual: 43, variance: -5, value: 70 },
    { audit: "A-1088", expected: 52, actual: 45, variance: -7, value: 98 },
    { audit: "A-1120", expected: 50, actual: 46, variance: -4, value: 56 },
    { audit: "A-1176", expected: 54, actual: 48, variance: -6, value: 84 },
    { audit: "A-1204", expected: 50, actual: 41, variance: -9, value: 126 },
    { audit: "A-1241", expected: 56, actual: 49, variance: -7, value: 98 },
    { audit: "A-1280", expected: 55, actual: 47, variance: -8, value: 112 },
    { audit: "A-1302", expected: 58, actual: 52, variance: -6, value: 84 },
    { audit: "A-1337", expected: 56, actual: 50, variance: -6, value: 84 },
    { audit: "A-1365", expected: 60, actual: 53, variance: -7, value: 98 },
  ],
  rca: [
    { name: "Stock sold", units: 42, value: 12800 },
    { name: "Expired", units: 31, value: 9100 },
    { name: "Missing", units: 26, value: 7800 },
    { name: "Misplaced", units: 18, value: 4400 },
    { name: "Damaged", units: 12, value: 3200 },
    { name: "Receiving error", units: 8, value: 2100 },
  ],
  expiry: [
    { period: "W1", expired: 44, nearExpiry: 91, unresolved: 11 },
    { period: "W2", expired: 52, nearExpiry: 104, unresolved: 14 },
    { period: "W3", expired: 39, nearExpiry: 96, unresolved: 9 },
    { period: "W4", expired: 61, nearExpiry: 118, unresolved: 18 },
    { period: "W5", expired: 48, nearExpiry: 101, unresolved: 12 },
  ],
  quarantine: [
    { stage: "Removal required", value: 286 },
    { stage: "Reported removed", value: 241 },
    { stage: "Received", value: 215 },
    { stage: "Removal verified", value: 188 },
    { stage: "Disposition verified", value: 133 },
  ],
  findings: [
    { name: "Critical", value: 12 },
    { name: "High", value: 28 },
    { name: "Medium", value: 47 },
    { name: "Low", value: 19 },
  ],
  corrective: [
    { stage: "Assigned", value: 46 },
    { stage: "In progress", value: 31 },
    { stage: "Pending verification", value: 18 },
    { stage: "Closed", value: 72 },
  ],
  repeatProblems: [
    { label: "MAGGI · Delhi Central", count: 9, cumulative: 24 },
    { label: "COLGATE · Gurugram", count: 7, cumulative: 43 },
    { label: "LAYS · Noida", count: 6, cumulative: 59 },
    { label: "TATA TEA · Delhi Saket", count: 5, cumulative: 73 },
    { label: "DOVE · Gurugram", count: 4, cumulative: 84 },
  ],
  quality: [
    { label: "Evidence complete", value: 92 },
    { label: "Quantity reconciled", value: 96 },
    { label: "RCA complete", value: 88 },
    { label: "Duplicate-free", value: 97 },
    { label: "High-assurance video", value: 74 },
  ],
  impact: [
    { period: "Apr", value: 226000 },
    { period: "May", value: 211000 },
    { period: "Jun", value: 198000 },
    { period: "Jul", value: 207000 },
    { period: "Aug", value: 192000 },
    { period: "Sep", value: 184000 },
  ],
  stores: [
    {
      id: "STR-DL-001",
      name: "Delhi Central 01",
      country: "India",
      city: "New Delhi",
      manager: "Rahul Sharma",
      lat: 28.6328,
      lng: 77.2197,
      coverage: 92,
      compliance: 89,
      variance: 28400,
      actions: 5,
      expiry: 31,
    },
    {
      id: "STR-DL-002",
      name: "Delhi Saket 02",
      country: "India",
      city: "New Delhi",
      manager: "Ayesha Khan",
      lat: 28.5245,
      lng: 77.2066,
      coverage: 86,
      compliance: 84,
      variance: 21600,
      actions: 3,
      expiry: 18,
    },
    {
      id: "STR-GG-003",
      name: "Gurugram DLF 03",
      country: "India",
      city: "Gurugram",
      manager: "Puneet Singh",
      lat: 28.4948,
      lng: 77.0888,
      coverage: 78,
      compliance: 76,
      variance: 41900,
      actions: 8,
      expiry: 46,
    },
    {
      id: "STR-ND-018",
      name: "Noida Sector 18",
      country: "India",
      city: "Noida",
      manager: "Meena Verma",
      lat: 28.5708,
      lng: 77.326,
      coverage: 81,
      compliance: 82,
      variance: 33200,
      actions: 6,
      expiry: 29,
    },
  ],
} as const;
