/**
 * Guest Demo ON fixtures for the real AiDigitalDashboardShell.
 * Shaped like live ops/digital payloads — no Supabase session required.
 */

import type { AiDashboardMetrics, DigitalDashboardMetrics } from "@/lib/dashboard-ai-digital";
import type { OpsAiDashboardData } from "@/lib/dashboard-ops-ai";
import { AISLIX } from "@/lib/aislix-theme";

const aiMetrics: AiDashboardMetrics = {
  auditCount: 42,
  productsIdentified: 186,
  brandsIdentified: 28,
  variantsIdentified: 64,
  categoriesIdentified: 9,
  totalFacings: 412,
  totalVisibleUnits: 980,
  avgConfidence: 94.2,
  verificationCoveragePct: 91,
  aiVsVerifiedUnitVariance: 3.2,
  aiUnitAccuracyPct: 96,
  aiFacingAccuracyPct: 93,
  brandShare: [
    { label: "Colgate", value: 34 },
    { label: "Sensodyne", value: 22 },
    { label: "Oral-B", value: 18 },
    { label: "Pepsodent", value: 14 },
    { label: "Others", value: 12 },
  ],
  categoryShare: [
    { label: "Oral Care", value: 38 },
    { label: "Beverages", value: 24 },
    { label: "Snacks", value: 20 },
    { label: "Personal Care", value: 18 },
  ],
  topProductsByFacings: [
    { label: "Colgate Total 120g", value: 28 },
    { label: "Sensodyne Repair 75ml", value: 18 },
    { label: "Oral-B Pro Expert", value: 14 },
    { label: "Lays Classic 52g", value: 12 },
  ],
  topProductsByUnits: [
    { label: "Colgate Total 120g", value: 64 },
    { label: "Coke 750ml", value: 48 },
    { label: "Sensodyne Repair 75ml", value: 36 },
  ],
  planogram: {
    applicable: true,
    expectedFacings: 480,
    actualFacings: 412,
    facingVariance: -68,
    facingPct: 85.8,
    compliancePct: 84,
  },
};

export const GUEST_OPS_AI_DASHBOARD: OpsAiDashboardData = {
  metrics: aiMetrics,
  executive: {
    audits: 42,
    completionPct: 84,
    openCritical: 3,
  },
  synopsis: {
    findingsOpen: 14,
    caOpen: 9,
    historyCount: 42,
    teamCount: 6,
  },
  completionMix: [
    { label: "Completed", value: 35, color: AISLIX.supermarketBorder },
    { label: "In progress", value: 5, color: AISLIX.warehouseBorder },
    { label: "Not started", value: 2, color: AISLIX.customBorder },
  ],
  auditTrend: [
    { label: "W1", value: 6 },
    { label: "W2", value: 8 },
    { label: "W3", value: 7 },
    { label: "W4", value: 9 },
    { label: "W5", value: 11 },
    { label: "W6", value: 10 },
  ],
  planogramByStore: [
    { label: "Koramangala", expected: 120, actual: 108 },
    { label: "Whitefield", expected: 100, actual: 82 },
    { label: "HSR", expected: 90, actual: 88 },
    { label: "Jayanagar", expected: 80, actual: 71 },
  ],
  topPerformers: [
    {
      storeId: "demo-1",
      storeName: "More Mart — Koramangala",
      completionPct: 96,
      compliancePct: 91,
      composite: 93,
      completed: 12,
      total: 12,
    },
    {
      storeId: "demo-3",
      storeName: "DMart — HSR Layout",
      completionPct: 92,
      compliancePct: 88,
      composite: 90,
      completed: 11,
      total: 12,
    },
  ],
  worstPerformers: [
    {
      storeId: "demo-2",
      storeName: "Big Bazaar — Whitefield",
      completionPct: 68,
      compliancePct: 74,
      composite: 71,
      completed: 8,
      total: 12,
    },
  ],
  lowComplianceStores: [
    { storeName: "Big Bazaar — Whitefield", compliancePct: 74 },
    { storeName: "Reliance Smart — Jayanagar", compliancePct: 79 },
  ],
  lastTen: [
    {
      id: "ga-1",
      scanId: "DEMO-8241",
      auditName: "Oral care · Aisle 7",
      templateName: "Shelf AI Audit",
      storeName: "More Mart — Koramangala",
      assigneeName: "Field Rep",
      assignerName: "Demo Manager",
      type: "AI",
      completionStage: "completed",
      date: new Date().toISOString(),
      scorePct: 91,
      relation: "assigned_by_me",
    },
    {
      id: "ga-2",
      scanId: "DEMO-8237",
      auditName: "Beverages · Aisle 3",
      templateName: "Shelf AI Audit",
      storeName: "Big Bazaar — Whitefield",
      assigneeName: "Store Lead",
      type: "AI",
      completionStage: "in_progress",
      date: new Date().toISOString(),
      scorePct: null,
      relation: "other",
    },
    {
      id: "ga-3",
      scanId: "DEMO-8229",
      auditName: "Snacks end-cap",
      templateName: "Shelf AI Audit",
      storeName: "Reliance Smart — Jayanagar",
      assigneeName: "Field Rep",
      type: "AI",
      completionStage: "completed",
      date: new Date(Date.now() - 86400000).toISOString(),
      scorePct: 76,
    },
  ],
  myAssignedAudits: [
    {
      id: "ga-asg-1",
      scanId: "DEMO-8241",
      auditName: "Oral care · Aisle 7",
      templateName: "Shelf AI Audit",
      storeName: "More Mart — Koramangala",
      assigneeName: "You (Guest)",
      assignerName: "Demo Manager",
      relation: "assigned_to_me",
      type: "AI",
      completionStage: "completed",
      date: new Date().toISOString(),
      dueAt: null,
      scorePct: 91,
    },
  ],
  lastReport: {
    scanId: "DEMO-8241",
    assignmentId: "ga-1",
    auditName: "Oral care · Aisle 7",
    storeName: "More Mart — Koramangala",
    date: new Date().toISOString(),
    compliancePct: 91,
    findingsCount: 2,
    confidencePct: 95,
    good: "Strong brand presence for Colgate; price tags readable.",
    attention: "2 low-facing SKUs and 1 empty slot on shelf 3.",
    nextAction: "Restock Oral-B Pro Expert and verify price tag on Sensodyne.",
    imageUrls: ["/home-hero-shelf.jpg"],
    completed: true,
  },
  deltas: {
    verificationCoverage: 2.4,
    planogramCompliance: 3.1,
    totalAudits: 4,
    avgConfidence: 0.8,
  },
  scopeLabel: "Guest demo · all stores",
  labeledDemo: true,
  previewDemo: true,
};

export const GUEST_DIGITAL_DASHBOARD: DigitalDashboardMetrics = {
  totalAudits: 19,
  completed: 12,
  inProgress: 4,
  pendingReview: 2,
  reauditRequested: 1,
  overdue: 3,
  completionPct: 63.2,
  onTimePct: 84,
  totalExpected: 380,
  totalActual: 342,
  netVariance: -38,
  absoluteVariance: 52,
  variancePct: -10,
  lastFive: [],
  lastTen: [
    {
      id: "gd-1",
      auditName: "Local Store Inventory Audit",
      templateName: "Local Store Inventory Audit",
      store: "W12 Gate Store",
      assignee: "Field Rep",
      date: new Date().toISOString(),
      status: "completed",
      expected: 20,
      actual: 14,
      variance: -6,
      findingsCount: 2,
      caCount: 1,
      reauditStatus: "—",
      scanId: "DEMO-DIG-1",
      relation: "assigned_by_me",
    },
    {
      id: "gd-2",
      auditName: "Supermarket OSA Check",
      templateName: "OSA Digital",
      store: "More Mart — Indiranagar",
      assignee: "Store Lead",
      date: new Date(Date.now() - 86400000).toISOString(),
      status: "in_progress",
      expected: 40,
      actual: null,
      variance: null,
      findingsCount: null,
      caCount: null,
      reauditStatus: "—",
      scanId: null,
    },
  ],
  fnv: {
    applicable: true,
    audits: 6,
    unitsInspected: 240,
    sellable: 210,
    damaged: 18,
    humanReview: 12,
    sellableRate: 87.5,
    damageRate: 7.5,
    humanReviewRate: 5,
  },
  varianceByStore: [
    { label: "Koramangala", value: -8 },
    { label: "Whitefield", value: -14 },
    { label: "HSR", value: -4 },
  ],
  varianceByCategory: [
    { label: "Oral Care", value: -6 },
    { label: "Snacks", value: -11 },
  ],
  caTotal: 22,
  caOpen: 9,
  caInProgress: 5,
  caOverdue: 3,
  caClosed: 5,
  caClosurePct: 22.7,
  caSlaPct: 78,
  caStatusMix: [
    { label: "Open", value: 9 },
    { label: "In progress", value: 5 },
    { label: "Overdue", value: 3 },
    { label: "Closed", value: 5 },
  ],
  potentialInventoryValueVariance: 18400,
  reauditImprovementPct: 12,
  recurringIssueRate: 18,
  labeledDemo: true,
  previewDemo: true,
};

/** Generic list rows for guest sidebar pages. */
export const GUEST_TABLE_ROWS = [
  {
    name: "Oral care · Aisle 7",
    store: "More Mart — Koramangala",
    status: "Completed",
    score: "91%",
    date: "Today",
  },
  {
    name: "Beverages · Aisle 3",
    store: "Big Bazaar — Whitefield",
    status: "In progress",
    score: "—",
    date: "Today",
  },
  {
    name: "Snacks end-cap",
    store: "Reliance Smart — Jayanagar",
    status: "Needs action",
    score: "76%",
    date: "Yesterday",
  },
  {
    name: "Personal care bay",
    store: "DMart — HSR Layout",
    status: "Completed",
    score: "88%",
    date: "2 days ago",
  },
] as const;
