#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src"
SKIP = {"routeTree.gen.ts", "types.ts"}

REPLACEMENTS = [
    ("Scan history", "Audit history"),
    ("Scan results", "Audit results"),
    ("No scan selected", "No audit selected"),
    ("Start a new scan", "Start a new audit"),
    ("Browse scan history", "Browse audit history"),
    ("Go to scan history", "Go to audit history"),
    ("Open scan history", "Open audit history"),
    ("Couldn't load this scan", "Couldn't load this audit"),
    ("We couldn't load this scan right now", "We couldn't load this audit right now"),
    ("This scan failed to process", "This audit failed to process"),
    ("Loading your assigned scan", "Loading your assigned audit"),
    ("Assigned scan", "Assigned audit"),
    ("previous scan", "previous audit"),
    ("Applies to this scan", "Applies to this audit"),
    ("this scan and", "this audit and"),
    ("per scan", "per audit"),
    ("ready to scan", "ready to audit"),
    ("Scan could not be started", "Audit could not be started"),
    ("New scan", "New audit"),
    ("Assign scan", "Assign audit"),
    ("Delete scan", "Delete audit"),
    ("Delete this scan?", "Delete this audit?"),
    ("All scans", "All audits"),
    ("Compare scans", "Compare audits"),
    ("Select two scans", "Select two audits"),
    ("two scans", "two audits"),
    ("both scans", "both audits"),
    ("comparison scans", "comparison audits"),
    ("each scan payload", "each audit payload"),
    ("each scan", "each audit"),
    ("older scans", "older audits"),
    ("No scans match", "No audits match"),
    ("No scans yet", "No audits yet"),
    ("scan history and", "audit history and"),
    ("Remaining scans", "Remaining audits"),
    ("Scan date", "Audit date"),
    ("Request re-scan", "Request re-audit"),
    ("re-scan shows", "re-audit shows"),
    ("then re-scan", "then re-audit"),
    ("Fix & re-scan", "Fix & re-audit"),
    ("Scan-based pricing", "Audit-based pricing"),
    ("scan volume does", "audit volume does"),
    ("5 scans a day", "5 audits a day"),
    ("scans a month", "audits a month"),
    ("Open a scan from", "Open an audit from"),
    ("run a new shelf scan", "run a new shelf audit"),
    ("AI breakdown of a single shelf scan", "AI breakdown of a single shelf audit"),
    (
        "Generated automatically by Aislix Retail Shelf Intelligence · Scan ",
        "Generated automatically by Aislix Retail Shelf Intelligence · Audit ",
    ),
    ("Could not delete this scan", "Could not delete this audit"),
    ("Try a different scan ID", "Try a different audit ID"),
    ("Search by scan ID", "Search by audit ID"),
    ("Filter by scan type", "Filter by audit type"),
    ("Run your first shelf scan", "Run your first shelf audit"),
    ("Couldn't load scan history", "Couldn't load audit history"),
    ("to scan your own shelves", "to audit your own shelves"),
    ("scan history and reports", "audit history and reports"),
    ('aislix-${data?.scan_id ?? "scan"}', 'aislix-${data?.scan_id ?? "audit"}'),
    ('aislix-${scanId ?? "scan"}', 'aislix-${scanId ?? "audit"}'),
    ('aislix-${data.scan_id || "scan"}', 'aislix-${data.scan_id || "audit"}'),
    (">Scan<", ">Audit<"),
    ("<TableHead>Scan</TableHead>", "<TableHead>Audit</TableHead>"),
    (" scans", " audits"),
    (" · {total.toLocaleString()} scans", " · {total.toLocaleString()} audits"),
    ("Metrics come straight from each scan payload", "Metrics come straight from each audit payload"),
    ("Fix → rescan → verify", "Fix → re-audit → verify"),
    ("Monthly scan usage", "Monthly audit usage"),
    ("Last scan ", "Last audit "),
    ("can scan and report", "can audit and report"),
    ("Full scan history", "Full audit history"),
    ("Start a scan", "Start an audit"),
    ("Assign a scan", "Assign an audit"),
    ("Start scan", "Start audit"),
    ("View scan", "View audit"),
    ("Start new scan", "Start new audit"),
    ("Sort scans", "Sort audits"),
    ("Search scans", "Search audits"),
    ("Search scan ", "Search audit "),
    ("Sort scan ", "Sort audit "),
    ("Scan ID", "Audit ID"),
    ("Scan metrics", "Audit metrics"),
    ("Scan attempts", "Audit attempts"),
    ("Scan volume", "Audit volume"),
    ("Scan usage", "Audit usage"),
    ("Scan packs", "Audit packs"),
    ("Scan pack", "Audit pack"),
    ("Scanning pauses", "Auditing pauses"),
    ("scanning limits", "auditing limits"),
    ("scanning may be paused", "auditing may be paused"),
    ("keep scanning", "keep auditing"),
    ("Start scanning", "Start auditing"),
    ("start scanning", "start auditing"),
    ("Rescan Required", "Re-audit Required"),
    ("Rescan to verify", "Re-audit to verify"),
    ("Fix & re-scan", "Fix & re-audit"),
    ("Fix shelf → re-scan → verify", "Fix shelf → re-audit → verify"),
    ("re-scan the same", "re-audit the same"),
    ("Go to my scans", "Go to my audits"),
    ("My Scans", "My Audits"),
    ("My scans", "My audits"),
    ("Assigned Scans", "Assigned Audits"),
    ("Assigned scans", "Assigned audits"),
    ("Team Scans", "Team Audits"),
    ("Demo Scans", "Demo Audits"),
    ("Demo scans", "Demo audits"),
    ("All Scans", "All Audits"),
    ("Browse all scans", "Browse all audits"),
    ("Recent scans", "Recent audits"),
    ("Total scans", "Total audits"),
    ("Scans used", "Audits used"),
    ("Scans remaining", "Audits remaining"),
    ("Scans (30 days)", "Audits (30 days)"),
    ("Last scan", "Last audit"),
    ("Scan completed", "Audit completed"),
    ("Scan failed", "Audit failed"),
    ("Scan cancelled", "Audit cancelled"),
    ("Scan not found", "Audit not found"),
    ("Scan assigned", "Audit assigned"),
    ("New Scan Assigned", "New Audit Assigned"),
    ("shelf scan task", "shelf audit task"),
    ("Scan share", "Audit share"),
    ("Shared scan report", "Shared audit report"),
    ("Scan report", "Audit report"),
    ("Scan details", "Audit details"),
    ("Scan date & time", "Audit date & time"),
    ("Scan again", "Audit again"),
    ("Scan is still", "Audit is still"),
    ("Scan service", "Audit service"),
    ("scan service", "audit service"),
    ("for this scan", "for this audit"),
    ("on this scan", "on this audit"),
    ("this scan's", "this audit's"),
    ("this scan.", "this audit."),
    ("this scan,", "this audit,"),
    ("the scan ", "the audit "),
    ("The scan ", "The audit "),
    ("a scan ", "an audit "),
    ("a scan.", "an audit."),
    ("a scan,", "an audit,"),
    ("a scan?", "an audit?"),
    ("a scan'", "an audit'"),
    ("a scan\"", "an audit\""),
    ("No scan ", "No audit "),
    ("no scan ", "no audit "),
    ("single scan", "single audit"),
    ("shelf scan", "shelf audit"),
    ("Shelf scan", "Shelf audit"),
    ("Shelf Scan", "Shelf Audit"),
    ("Scan a ", "Audit a "),
    ("Scan an ", "Audit an "),
    ("Scan the ", "Audit the "),
    ("Scan your ", "Audit your "),
    ("Scan to ", "Audit to "),
    ("Scan and ", "Audit and "),
    ("Scan or ", "Audit or "),
    ("Scan ·", "Audit ·"),
    ("Scan type", "Audit type"),
    ("Scan quota", "Audit quota"),
    ("Scan limits", "Audit limits"),
    ("Scan limit", "Audit limit"),
    ("Scan allowance", "Audit allowance"),
    ("Images per scan", "Images per audit"),
    ("Scans included", "Audits included"),
    ("Unlimited scans", "Unlimited audits"),
    ("unlimited scans", "unlimited audits"),
    ("free scans", "free audits"),
    ("Free scans", "Free audits"),
    ("demo scans", "demo audits"),
    ("Demo scan", "Demo audit"),
    ("Compliance scan", "Compliance audit"),
    ("Free scan", "Free audit"),
    ("Ad hoc scan", "Ad hoc audit"),
    ("Weekly scan target", "Weekly audit target"),
    ("last scan ", "last audit "),
    ("Scanning", "Auditing"),
    ("scanning", "auditing"),
    ("Scanned", "Audited"),
    ("scanned", "audited"),
]

for path in ROOT.rglob("*"):
    if path.suffix not in {".ts", ".tsx"} or path.name in SKIP:
        continue
    text = path.read_text(encoding="utf-8")
    orig = text
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    if text != orig:
        path.write_text(text, encoding="utf-8")
        print(path.relative_to(ROOT.parent))

print("done")
