import type { AskAislixSuggestionItem } from "./ask-aislix-suggestions.types";

const T = {
  kpi: "get_kpi",
  summary: "get_audit_summary",
  overdue: "get_overdue_audits",
  variance: "get_inventory_variance",
  findings: "get_findings",
  actions: "get_corrective_actions",
  trends: "get_audit_trends",
  stores: "get_store_performance",
  expiry: "get_expiry_risk",
  evidence: "get_audit_evidence_images",
  recurring: "get_recurring_issues",
} as const;

/**
 * Internal Ask Aislix suggestion library.
 * Only questions backed by wired tools are included.
 */
export const ASK_AISLIX_SUGGESTION_LIBRARY: AskAislixSuggestionItem[] = [
  // ── Universal / cross-role ──────────────────────────────────────────────
  {
    id: "univ_audit_completion_trend",
    text: "Show audit completion trend over the last 30 days",
    roles: ["universal"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.trends],
  },
  {
    id: "univ_recurring_locations",
    text: "Which locations have the highest recurring issues?",
    roles: ["universal"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring],
  },
  {
    id: "univ_recurring_findings",
    text: "Which findings keep appearing across audits?",
    roles: ["universal"],
    category: "recurring",
    icon: "findings",
    requiredTools: [T.recurring],
  },
  {
    id: "univ_overdue_actions",
    text: "Which corrective actions are overdue?",
    roles: ["universal"],
    category: "actions",
    icon: "actions",
    requiredTools: [T.actions, T.overdue],
  },
  {
    id: "univ_reopened_issues",
    text: "Which issues reappeared after being marked resolved?",
    roles: ["universal"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring],
  },
  {
    id: "univ_compare_month",
    text: "Compare this month with last month",
    roles: ["universal"],
    category: "comparison",
    icon: "comparison",
    requiredTools: [T.trends],
  },
  {
    id: "univ_improved_locations",
    text: "Which locations improved the most this month?",
    roles: ["universal"],
    category: "stores",
    icon: "stores",
    requiredTools: [T.stores],
  },
  {
    id: "univ_declined_locations",
    text: "Which locations declined the most this month?",
    roles: ["universal"],
    category: "stores",
    icon: "stores",
    requiredTools: [T.stores],
  },
  {
    id: "univ_top_failures",
    text: "Show me the top recurring audit failures",
    roles: ["universal"],
    category: "recurring",
    icon: "findings",
    requiredTools: [T.recurring],
  },
  {
    id: "univ_compliance_change",
    text: "Why did compliance change this month?",
    roles: ["universal"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.trends, T.findings],
  },
  {
    id: "univ_open_findings",
    text: "How many open findings do we have right now?",
    roles: ["universal"],
    category: "findings",
    icon: "findings",
    requiredTools: [T.kpi, T.findings],
  },
  {
    id: "univ_critical_findings",
    text: "Show critical findings that need attention",
    roles: ["universal"],
    category: "findings",
    icon: "findings",
    requiredTools: [T.findings, T.kpi],
  },
  {
    id: "univ_overdue_audits",
    text: "Which audits are overdue right now?",
    roles: ["universal"],
    category: "audit",
    icon: "audit",
    requiredTools: [T.overdue],
  },
  {
    id: "univ_evidence_recent",
    text: "Show me the latest audit evidence images",
    roles: ["universal"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence],
  },

  // ── Supermarket ─────────────────────────────────────────────────────────
  {
    id: "sm_evidence_city",
    text: "Show me the latest shelf images from {{city}} stores",
    roles: ["supermarket"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence],
  },
  {
    id: "sm_evidence_failed",
    text: "Show shelf images from stores with failed audits",
    roles: ["supermarket"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence, T.stores],
  },
  {
    id: "sm_evidence_actions",
    text: "Show before/after evidence for recent corrective actions",
    roles: ["supermarket"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence, T.actions],
  },
  {
    id: "sm_variance_top",
    text: "Which SKUs had the highest inventory variance this month?",
    roles: ["supermarket"],
    category: "inventory",
    icon: "inventory",
    requiredTools: [T.variance],
  },
  {
    id: "sm_variance_trend",
    text: "What was inventory variance trend over the last 30 days?",
    roles: ["supermarket"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.variance, T.trends],
  },
  {
    id: "sm_oos_recurring",
    text: "Which SKUs repeatedly went out of stock?",
    roles: ["supermarket"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.variance],
  },
  {
    id: "sm_expiry_stores",
    text: "Which stores have the highest expiry risk?",
    roles: ["supermarket"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry],
  },
  {
    id: "sm_expiry_products",
    text: "Show products nearing expiry in my supermarkets",
    roles: ["supermarket"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry],
  },
  {
    id: "sm_store_risk",
    text: "Which supermarkets are at the highest audit risk?",
    roles: ["supermarket"],
    category: "stores",
    icon: "stores",
    requiredTools: [T.stores],
  },
  {
    id: "sm_recurring_findings",
    text: "Which audit issues keep repeating in supermarkets?",
    roles: ["supermarket"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring],
  },

  // ── FMCG / Distributor ──────────────────────────────────────────────────
  {
    id: "fmcg_outlet_compliance",
    text: "Which outlets have the lowest execution compliance?",
    roles: ["fmcg", "distributor"],
    category: "stores",
    icon: "stores",
    requiredTools: [T.stores],
  },
  {
    id: "fmcg_outlet_trend",
    text: "Show outlet compliance trend this month",
    roles: ["fmcg", "distributor"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.trends, T.stores],
  },
  {
    id: "fmcg_failed_outlets",
    text: "Which outlets repeatedly failed retail execution audits?",
    roles: ["fmcg", "distributor"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.stores],
  },
  {
    id: "fmcg_oos_rate",
    text: "Which SKUs have the highest OOS rate across outlets?",
    roles: ["fmcg", "distributor"],
    category: "inventory",
    icon: "inventory",
    requiredTools: [T.variance, T.recurring],
  },
  {
    id: "fmcg_distributor_compare",
    text: "Compare distributor performance this month vs last month",
    roles: ["fmcg", "distributor"],
    category: "comparison",
    icon: "comparison",
    requiredTools: [T.stores, T.trends],
  },
  {
    id: "fmcg_recurring_findings",
    text: "Which distributors have the most recurring findings?",
    roles: ["fmcg", "distributor"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.stores],
  },
  {
    id: "fmcg_expiry_outlets",
    text: "Which outlets have products nearing expiry?",
    roles: ["fmcg", "distributor"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry],
  },
  {
    id: "fmcg_evidence_outlets",
    text: "Show audit evidence from low-compliance outlets",
    roles: ["fmcg", "distributor"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence, T.stores],
  },
  {
    id: "fmcg_overdue_actions",
    text: "Which outlet corrective actions are overdue?",
    roles: ["fmcg", "distributor"],
    category: "actions",
    icon: "actions",
    requiredTools: [T.actions, T.overdue],
  },

  // ── Local store ─────────────────────────────────────────────────────────
  {
    id: "local_variance_top",
    text: "Which products have the biggest inventory variance?",
    roles: ["local"],
    category: "inventory",
    icon: "inventory",
    requiredTools: [T.variance],
  },
  {
    id: "local_variance_trend",
    text: "What was my inventory variance trend over 30 days?",
    roles: ["local"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.variance, T.trends],
  },
  {
    id: "local_shortages",
    text: "Which SKUs repeatedly showed shortages?",
    roles: ["local"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.variance],
  },
  {
    id: "local_expiry",
    text: "Which products are nearing expiry?",
    roles: ["local"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry],
  },
  {
    id: "local_expiry_category",
    text: "Which categories have the highest expiry risk?",
    roles: ["local"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry],
  },
  {
    id: "local_shelf_images",
    text: "Show me the latest shelf images",
    roles: ["local"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence],
  },
  {
    id: "local_recurring_issues",
    text: "Which audit issues keep repeating?",
    roles: ["local"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring],
  },
  {
    id: "local_overdue_actions",
    text: "Which corrective actions are overdue?",
    roles: ["local"],
    category: "actions",
    icon: "actions",
    requiredTools: [T.actions, T.overdue],
  },
  {
    id: "local_reopened",
    text: "Which findings were reopened after being closed?",
    roles: ["local"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring],
  },

  // ── Dark store ──────────────────────────────────────────────────────────
  {
    id: "ds_variance_stores",
    text: "Which dark stores have the highest inventory variance?",
    roles: ["darkstore"],
    category: "inventory",
    icon: "inventory",
    requiredTools: [T.variance, T.stores],
  },
  {
    id: "ds_variance_trend",
    text: "What was inventory variance over the last 30 days?",
    roles: ["darkstore"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.variance, T.trends],
  },
  {
    id: "ds_shortages",
    text: "Which SKUs repeatedly show shortages?",
    roles: ["darkstore"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.variance],
  },
  {
    id: "ds_expiry_stores",
    text: "Which dark stores have the highest expiry risk?",
    roles: ["darkstore"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry, T.stores],
  },
  {
    id: "ds_expiry_products",
    text: "Show products nearing expiry in dark stores",
    roles: ["darkstore"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry],
  },
  {
    id: "ds_evidence_low",
    text: "Show shelf images from dark stores with low compliance",
    roles: ["darkstore"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence, T.stores],
  },
  {
    id: "ds_evidence_failed",
    text: "Show evidence from failed inventory audits",
    roles: ["darkstore"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence, T.variance],
  },
  {
    id: "ds_recurring",
    text: "Which dark store issues keep recurring?",
    roles: ["darkstore"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring],
  },

  // ── Warehouse ───────────────────────────────────────────────────────────
  {
    id: "wh_variance",
    text: "Which warehouses have the highest inventory variance?",
    roles: ["warehouse"],
    category: "inventory",
    icon: "inventory",
    requiredTools: [T.variance, T.stores],
  },
  {
    id: "wh_variance_trend",
    text: "What was inventory accuracy trend over 30 days?",
    roles: ["warehouse"],
    category: "trend",
    icon: "trend",
    requiredTools: [T.variance, T.trends],
  },
  {
    id: "wh_sku_discrepancies",
    text: "Which SKUs repeatedly show inventory discrepancies?",
    roles: ["warehouse"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.variance],
  },
  {
    id: "wh_expiry",
    text: "Which warehouses have the highest expiry risk?",
    roles: ["warehouse"],
    category: "expiry",
    icon: "expiry",
    requiredTools: [T.expiry, T.stores],
  },
  {
    id: "wh_recurring",
    text: "Which warehouse zones have recurring compliance issues?",
    roles: ["warehouse"],
    category: "recurring",
    icon: "recurring",
    requiredTools: [T.recurring, T.stores],
  },
  {
    id: "wh_evidence",
    text: "Show evidence from failed warehouse audits",
    roles: ["warehouse"],
    category: "evidence",
    icon: "image",
    requiredTools: [T.evidence],
  },
  {
    id: "wh_overdue",
    text: "Which warehouse corrective actions are overdue?",
    roles: ["warehouse"],
    category: "actions",
    icon: "actions",
    requiredTools: [T.actions, T.overdue],
  },
  {
    id: "wh_compare",
    text: "Compare warehouse audit completion this month vs last",
    roles: ["warehouse"],
    category: "comparison",
    icon: "comparison",
    requiredTools: [T.trends],
  },
];
