/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssignScanRouteImport } from './routes/assign-scan'
import { Route as AssignedScansRouteImport } from './routes/assigned-scans'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CorrectiveActionsRouteImport } from './routes/corrective-actions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as MyScansRouteImport } from './routes/my-scans'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoreMasterRouteImport } from './routes/store-master'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreIdRouteImport } from './routes/stores.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignScanRoute = AssignScanRouteImport.update({
  id: '/assign-scan',
  path: '/assign-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignedScansRoute = AssignedScansRouteImport.update({
  id: '/assigned-scans',
  path: '/assigned-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectiveActionsRoute = CorrectiveActionsRouteImport.update({
  id: '/corrective-actions',
  path: '/corrective-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const MyScansRoute = MyScansRouteImport.update({
  id: '/my-scans',
  path: '/my-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreMasterRoute = StoreMasterRouteImport.update({
  id: '/store-master',
  path: '/store-master',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assign-scan': typeof AssignScanRoute
  '/assigned-scans': typeof AssignedScansRoute
  '/billing': typeof BillingRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corrective-actions': typeof CorrectiveActionsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/my-scans': typeof MyScansRoute
  '/organization': typeof OrganizationRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/store-master': typeof StoreMasterRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/scan': typeof ApiScanRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assign-scan': typeof AssignScanRoute
  '/assigned-scans': typeof AssignedScansRoute
  '/billing': typeof BillingRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corrective-actions': typeof CorrectiveActionsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/my-scans': typeof MyScansRoute
  '/organization': typeof OrganizationRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/store-master': typeof StoreMasterRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/scan': typeof ApiScanRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assign-scan': typeof AssignScanRoute
  '/assigned-scans': typeof AssignedScansRoute
  '/billing': typeof BillingRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corrective-actions': typeof CorrectiveActionsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/my-scans': typeof MyScansRoute
  '/organization': typeof OrganizationRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/store-master': typeof StoreMasterRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/scan': typeof ApiScanRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assign-scan'
    | '/assigned-scans'
    | '/billing'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/corrective-actions'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/forgot-password'
    | '/history'
    | '/how-it-works'
    | '/login'
    | '/logout'
    | '/my-scans'
    | '/organization'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/processing'
    | '/profile'
    | '/refunds'
    | '/report'
    | '/reports'
    | '/reset-password'
    | '/results'
    | '/scan'
    | '/security'
    | '/settings'
    | '/signup'
    | '/store-master'
    | '/team'
    | '/terms'
    | '/upload'
    | '/users'
    | '/verify-email'
    | '/api/scan'
    | '/stores/$storeId'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assign-scan'
    | '/assigned-scans'
    | '/billing'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/corrective-actions'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/forgot-password'
    | '/history'
    | '/how-it-works'
    | '/login'
    | '/logout'
    | '/my-scans'
    | '/organization'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/processing'
    | '/profile'
    | '/refunds'
    | '/report'
    | '/reports'
    | '/reset-password'
    | '/results'
    | '/scan'
    | '/security'
    | '/settings'
    | '/signup'
    | '/store-master'
    | '/team'
    | '/terms'
    | '/upload'
    | '/users'
    | '/verify-email'
    | '/api/scan'
    | '/stores/$storeId'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assign-scan'
    | '/assigned-scans'
    | '/billing'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/corrective-actions'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/forgot-password'
    | '/history'
    | '/how-it-works'
    | '/login'
    | '/logout'
    | '/my-scans'
    | '/organization'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/processing'
    | '/profile'
    | '/refunds'
    | '/report'
    | '/reports'
    | '/reset-password'
    | '/results'
    | '/scan'
    | '/security'
    | '/settings'
    | '/signup'
    | '/store-master'
    | '/team'
    | '/terms'
    | '/upload'
    | '/users'
    | '/verify-email'
    | '/api/scan'
    | '/stores/$storeId'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssignScanRoute: typeof AssignScanRoute
  AssignedScansRoute: typeof AssignedScansRoute
  BillingRoute: typeof BillingRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CorrectiveActionsRoute: typeof CorrectiveActionsRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MyScansRoute: typeof MyScansRoute
  OrganizationRoute: typeof OrganizationRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessingRoute: typeof ProcessingRoute
  ProfileRoute: typeof ProfileRoute
  RefundsRoute: typeof RefundsRoute
  ReportRoute: typeof ReportRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  ScanRoute: typeof ScanRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StoreMasterRoute: typeof StoreMasterRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  UsersRoute: typeof UsersRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiScanRoute: typeof ApiScanRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assign-scan': {
      id: '/assign-scan'
      path: '/assign-scan'
      fullPath: '/assign-scan'
      preLoaderRoute: typeof AssignScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assigned-scans': {
      id: '/assigned-scans'
      path: '/assigned-scans'
      fullPath: '/assigned-scans'
      preLoaderRoute: typeof AssignedScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrective-actions': {
      id: '/corrective-actions'
      path: '/corrective-actions'
      fullPath: '/corrective-actions'
      preLoaderRoute: typeof CorrectiveActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-scans': {
      id: '/my-scans'
      path: '/my-scans'
      fullPath: '/my-scans'
      preLoaderRoute: typeof MyScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-master': {
      id: '/store-master'
      path: '/store-master'
      fullPath: '/store-master'
      preLoaderRoute: typeof StoreMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssignScanRoute: AssignScanRoute,
  AssignedScansRoute: AssignedScansRoute,
  BillingRoute: BillingRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CorrectiveActionsRoute: CorrectiveActionsRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MyScansRoute: MyScansRoute,
  OrganizationRoute: OrganizationRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessingRoute: ProcessingRoute,
  ProfileRoute: ProfileRoute,
  RefundsRoute: RefundsRoute,
  ReportRoute: ReportRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  ScanRoute: ScanRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StoreMasterRoute: StoreMasterRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  UsersRoute: UsersRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiScanRoute: ApiScanRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
